/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.m3;

import com.m3.files.Folders;
import com.m3.util.Files;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author ACER
 */
public class Main extends javax.swing.JFrame {

    public Folders folders = Folders.getInstance();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        if (!folders.isEmpty()) setText();
    }

    public void setText() {
        modsFolderLabel.setText(folders.getModsFolder().getPath());
        M3FolderLabel.setText(folders.getM3Folder().getPath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modsFolderLabel = new javax.swing.JLabel();
        modsFolderBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        M3FolderLabel = new javax.swing.JLabel();
        m3FolderBtn = new javax.swing.JButton();
        addModsToVersionBtn = new javax.swing.JButton();
        addNewVersionBtn = new javax.swing.JButton();
        backupBtn = new javax.swing.JButton();
        viewBackupBtn = new javax.swing.JButton();
        viewsecondBackupBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        setCurrentBtn = new javax.swing.JButton();
        renameCurrentBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1200));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Minecraft Mods Folder:");

        modsFolderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modsFolderLabel.setText("(not set)");

        modsFolderBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modsFolderBtn.setText("Change Mods Folder");
        modsFolderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modsFolderBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("M3 Folder");

        M3FolderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        M3FolderLabel.setText("(not set)");

        m3FolderBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        m3FolderBtn.setText("Change M3 Folder");
        m3FolderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3FolderBtnActionPerformed(evt);
            }
        });

        addModsToVersionBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addModsToVersionBtn.setText("Add Mods To Version");
        addModsToVersionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModsToVersionBtnActionPerformed(evt);
            }
        });

        addNewVersionBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addNewVersionBtn.setText("Add New Version");
        addNewVersionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewVersionBtnActionPerformed(evt);
            }
        });

        backupBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backupBtn.setText("<html>Backup Current Mods Folder (Automatic)</html>");
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });

        viewBackupBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewBackupBtn.setText("View Backup Folder");
        viewBackupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBackupBtnActionPerformed(evt);
            }
        });

        viewsecondBackupBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewsecondBackupBtn.setText("Second Backup Folder");
        viewsecondBackupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsecondBackupBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(m3FolderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modsFolderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addModsToVersionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addNewVersionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewsecondBackupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewBackupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(M3FolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modsFolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(modsFolderLabel)
                .addGap(18, 18, 18)
                .addComponent(modsFolderBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(M3FolderLabel)
                .addGap(18, 18, 18)
                .addComponent(m3FolderBtn)
                .addGap(76, 76, 76)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(addModsToVersionBtn)
                .addGap(18, 18, 18)
                .addComponent(addNewVersionBtn)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewBackupBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewsecondBackupBtn))
                    .addComponent(backupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jSeparator1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jSeparator1.setMinimumSize(new java.awt.Dimension(20, 0));
        getContentPane().add(jSeparator1, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(800, 1200));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Versions");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Click a version to replace the mods folder with that version's mods");

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("jRadioButton1");

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton3.setText("jRadioButton1");

        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton4.setText("jRadioButton1");

        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton5.setText("jRadioButton1");

        setCurrentBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setCurrentBtn.setText("Set Current Mods Folder Version");
        setCurrentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCurrentBtnActionPerformed(evt);
            }
        });

        renameCurrentBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        renameCurrentBtn.setText("Rename Current Selected Mod");
        renameCurrentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameCurrentBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("M3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(renameCurrentBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setCurrentBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addComponent(setCurrentBtn)
                .addGap(18, 18, 18)
                .addComponent(renameCurrentBtn)
                .addGap(44, 44, 44)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addGap(78, 78, 78)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modsFolderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modsFolderBtnActionPerformed
        File chosenFolder = Files.folderChooser(this);
        if (chosenFolder == null)
            JOptionPane.showMessageDialog(this, "Please select your mods folder.", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            folders = new Folders(chosenFolder, true);
            setText();
        }

    }//GEN-LAST:event_modsFolderBtnActionPerformed

    private void m3FolderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3FolderBtnActionPerformed
        if (folders.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select your mods folder first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        File chosenFolder = Files.folderChooser(this);
        if (chosenFolder == null)
            JOptionPane.showMessageDialog(this, "Please select your M3 folder.", "Errpr", JOptionPane.ERROR_MESSAGE);
        else {
            folders.setM3Folder(chosenFolder);
            setText();
        }
    }//GEN-LAST:event_m3FolderBtnActionPerformed

    private void addNewVersionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewVersionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewVersionBtnActionPerformed

    private void addModsToVersionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModsToVersionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addModsToVersionBtnActionPerformed

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backupBtnActionPerformed

    private void viewBackupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBackupBtnActionPerformed
        try {
            Desktop.getDesktop().open(Folders.m3Files.getBackupsFolder());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_viewBackupBtnActionPerformed

    private void viewsecondBackupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsecondBackupBtnActionPerformed
        try {
            Desktop.getDesktop().open(Folders.homeFiles.BACKUP_FOLDER);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_viewsecondBackupBtnActionPerformed

    private void setCurrentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCurrentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setCurrentBtnActionPerformed

    private void renameCurrentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameCurrentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renameCurrentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel M3FolderLabel;
    private javax.swing.JButton addModsToVersionBtn;
    private javax.swing.JButton addNewVersionBtn;
    private javax.swing.JButton backupBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton m3FolderBtn;
    private javax.swing.JButton modsFolderBtn;
    private javax.swing.JLabel modsFolderLabel;
    private javax.swing.JButton renameCurrentBtn;
    private javax.swing.JButton setCurrentBtn;
    private javax.swing.JButton viewBackupBtn;
    private javax.swing.JButton viewsecondBackupBtn;
    // End of variables declaration//GEN-END:variables
}
